### ISSUE TITLE
Set up Pages on this repository.

### ISSUE THREAD

**Issue by eleanorfrajka** [ifmeo-hamburg/WBTSdata#19]
Ok, last step!
https://eleanorfrajka.github.io/template-project/github.html#activating-github-io-projectname

**Comment by tillmrtz** [comment]
I set up the Pages for this repository. The url can be found on the main page: 
<img width="364" alt="image" src="https://github.com/user-attachments/assets/b09c117e-d496-4b2f-9c92-89fbbcf3cea7" />
