### ISSUE TITLE
Merge clobbers attributes

### ISSUE THREAD

**Issue by eleanorfrajka** [ifmeo-hamburg/WBTSdata#5]
Merging files clobbers the attributes.  I think this is OK since the main output is a file per year.   But rather that the method I put in `demo.ipynb`, could be another function `merge_years()` to do this, and make a choice on the attributes.

An option could be to create a list of names, separated by comma, and then retain only the unique contributor names.  Same for project_id.

`geospatial` limits could be the overall maximum and overall minimum.
`time_cruise*` could be the overall max and min.

**Comment by tillmrtz** [comment]
I create the function merge_dataset to merge all years. The global attributes that depend on the individual cruise are updated within the function: 
![image](https://github.com/user-attachments/assets/b21442e6-f7cb-48ab-ac74-224fbf74d272)

**Comment by tillmrtz** [comment]
Task finished
