### ISSUE TITLE
feat: merge_years to handle years when no LADCP data are present

### ISSUE THREAD

**Issue by eleanorfrajka** [ifmeo-hamburg/WBTSdata#6]
It may be advantageous to create a merge to handle years when there were no LADCP data (e.g. 2021 and 2023?).  It could either be: a separate merge of CTD vs LADCP data, or a merge that puts NaNs for LADCP variables when there were no LADCP data.  This way, if someone is using the merged file for only the CTD data, they don't lose years.

**Comment by tillmrtz** [comment]
I'll try to implement this later

**Comment by tillmrtz** [comment]
I changed the function merge_dataset and the algorithm in load_dataset notebook to fill nan values for the missing LADCP data: 
![image](https://github.com/user-attachments/assets/d3112cf7-b433-43b6-b0da-2304f28f6431)
