### ISSUE TITLE
docs: Add documentation using sphinx with Github actions

### ISSUE THREAD

**Issue by eleanorfrajka** [ifmeo-hamburg/WBTSdata#8]
See details here: https://eleanorfrajka.github.io/template-project/github.html#github-action-to-build-documentation
- [x] #18
- [x] #17
- [x] #16
- [x] #19

Set up the repository to automatically generate documentation of the code.

**Comment by eleanorfrajka** [comment]
Ok - after a little faff, I think this is ready to go.  You can see in the "branches" that there is now a "gh-pages" branch.

**Comment by tillmrtz** [comment]
Completed the last step: Setting up Pages on repository
